### ISSUE TITLE
Dataset preprocessing

### ISSUE THREAD

**Issue by guosyjlu** [WenjieWWJ/DenoisingRec#2]
Hi, thanks for your great work. I'm very interested in your paper.
Could you please provide the dataset preprocessing codes for generating the uploaded data?  If not, could you give some step-by-step descriptions?
Thanks for any possible help.

**Comment by May2333** [comment]
Hi, I'm also wondering about the dataset preprocessing. 
Did you figure it out? 
Any reply will be helpful!

**Comment by guosyjlu** [comment]
> Hi, I'm also wondering about the dataset preprocessing. Did you figure it out? Any reply will be helpful!

Hi, you can try NeuRec: https://github.com/wubinzzu/NeuRec

**Comment by May2333** [comment]
Thanks a lot.
But I looked through the NeuRec code, and the data processing is different from this DenoisyRec..
Or I didn't get the right way to read it?
Thanks again!
Thanks again!

**Comment by May2333** [comment]
Thanks a lot.
But I looked through the NeuRec code, and the data processing is different from this DenoisyRec..
Or I didn't get the right way to read it?
Thanks again!

**Comment by guosyjlu** [comment]
> Thanks a lot. But I looked through the NeuRec code, and the data processing is different from this DenoisyRec.. Or I didn't get the right way to read it? Thanks again!

Yes, I reimplement the process based on the processing code of NeuRec, which is not that difficult.

**Comment by May2333** [comment]
> > Thanks a lot. But I looked through the NeuRec code, and the data processing is different from this DenoisyRec.. Or I didn't get the right way to read it? Thanks again!
> 
> Yes, I reimplement the process based on the processing code of NeuRec, which is not that difficult.
Ok, I'll try it again.
Thanks again and again :)

**Comment by May2333** [comment]
>> Yes, I reimplement the process based on the processing code of NeuRec, which is not that difficult.

Ok, I'll try it again.
Thanks again and again :)
