### ISSUE TITLE
About evaluation on Recall

### ISSUE THREAD

**Issue by Guanyu-Lin** [WenjieWWJ/DenoisingRec#3]
Hi, when I perform "python inference.py --dataset=yelp --model=GMF --drop_rate=0.1 --num_gradual=30000 --gpu=0", I obtain Recall@50 and Recall@100 both at 0.0000 though NDCG is the same as that of the paper. Is there something wrong in your source code?

**Comment by WenjieWWJ** [comment]
hi, thanks for the question. I didn't find this issue in the previous experiments. Could you please check the calculation of Recall in the evaluation as well as its print-out? Since NDCG is normal, the model output should be correct.

**Comment by Guanyu-Lin** [comment]
Thanks for your kind reply, it results from my python 2, where the operation of division will return int value.
